const search = [
    {item:"turtle",
        results: [
            {id: 1,
            url: "https://en.wikipedia.org/wiki/Turtle",
            breadcrumb: "https://en.wikipedia.org > wiki > Turtle",        
            title: "Turtle - Wikipedia",
            description: "Turtles are an order of reptiles known as Testudines, characterized by a shell developed mainly from their ribs. Modern turtles are divided into two major ..."},
            {id: 2,
                url: "https://www.britannica.com/animal/turtle-reptile",
                breadcrumb: "https://www.britannica.com > ... > Reptile",        
                title: "turtle | Species, Classification, & Facts | Britannica",
                description: "turtle, (order Testudines), any reptile with a body encased in a bony shell, including tortoises. Although numerous animals, from invertebrates to mammals, ..."},
            {id: 3,
                url: "https://www.britannica.com/story/whats-the-difference-between-a-turtle-and-a-tortoise",
                breadcrumb: "https://www.britannica.com > Demystified > Science",        
                title: "What's the Difference Between a Turtle and a Tortoise?",
                description: "All tortoises are in fact turtles—that is, they belong to the order Testudines or Chelonia, reptiles having bodies encased in a bony shell—but not all turtles ..."},
            {id: 4,
                url: "https://www.worldwildlife.org/species/sea-turtle",
                breadcrumb: "https://www.worldwildlife.org > species > sea-turtle",        
                title: "Sea Turtle | Species | WWF - World Wildlife Fund",
                description: "Sea turtles are the live representatives of a group of reptiles that have existed on Earth and traveled our seas for the last 100 million years. Turtles have ..."},
            {id: 5,
                url: "https://docs.python.org/3/library/turtle.html",
                breadcrumb: "https://docs.python.org > library > turtle",        
                title: "turtle — Turtle graphics — Python 3.10.7 documentation",
                description: "Turtle graphics is a popular way for introducing programming to kids. ... Turtle can draw intricate shapes using programs that repeat simple moves."},
            {id: 6,
                url: "https://en.wiktionary.org/wiki/turtle",
                breadcrumb: "https://en.wiktionary.org > wiki > turtle",        
                title: "turtle - Wiktionary",
                description: "NounEdit · (zoology, US, Canada) Any land or marine reptile of the order Testudines, characterised by a protective shell enclosing its body. · (zoology, Australia ..."},
            {id: 7,
                url: "https://www.wwf.org.uk/learn/fascinating-facts/marine-turtles",
                breadcrumb: "https://www.wwf.org.uk > learn > fascinating-facts > ma...",        
                title: "Top 10 facts about marine turtles - WWF-UK",
                description: "There are seven species of marine turtle. Marine turtles were around more than 100 million years ago - and lived alongside dinosaurs. These days, scientists ..."},
            {id: 8,
                url: "https://emojipedia.org/turtle/",
                breadcrumb: "https://emojipedia.org > turtle",        
                title: "Turtle Emoji - Emojipedia",
                description: "Emoji Meaning. A turtle, a slow-moving reptile with a shell. Depicted as a light-green turtle in full profile on all fours facing left, ..."},
            {id: 9,
                url: "https://www.seeturtles.org/why-are-sea-turtles-important",
                breadcrumb: "https://www.seeturtles.org > why-are-sea-turtles-important",        
                title: "Why Are Sea Turtles Important",
                description: "Turtle nesting helps beaches. The nutrients left behind by eggs and hatchlings that don't survive provide an important source for coastal vegetation. Hatchlings ..."},
            {id: 10,
                url: "http://seaturtle.org/",
                breadcrumb: "http://seaturtle.org",        
                title: "SEATURTLE.ORG - Global Sea Turtle Network",
                description: "Organizing the world's sea turtle information and making it universally accessible and useful."}
        ]},
    {item:"tiger",
        results: [
            {id: 1,
                url: "https://flyingtiger.com/",
                breadcrumb: "https://flyingtiger.com",        
                title: "Flying Tiger Copenhagen - Shop Online",
                description: "At Flying Tiger Copenhagen, we design products to make you feel good - Find inspirational products in our new webshop. Flying Tiger Copenhagen."},
            {id: 2,
                url: "https://en.wikipedia.org/wiki/Tiger",
                breadcrumb: "https://en.wikipedia.org > wiki > Tiger",        
                title: "Tiger - Wikipedia",
                description: "The tiger (Panthera tigris) is the largest living cat species and a member of the genus Panthera. It is most recognisable for its dark vertical stripes on ..."},
            {id: 3,
                url: "https://en.wikipedia.org/wiki/Tiger_I",
                breadcrumb: "https://en.wikipedia.org > wiki > Tiger_I",        
                title: "Tiger I - Wikipedia",
                description: "The Tiger I ( listen (help·info)) was a German heavy tank of World War II that operated beginning in 1942 in Africa and in the Soviet Union, usually in ..."},
            {id: 4,
                url: "https://www.worldwildlife.org/species/tiger",
                breadcrumb: "https://www.worldwildlife.org > species > tiger",        
                title: "Tiger | Species | WWF - World Wildlife Fund",
                description: "One of the world's largest, and most uniquely-adapted, tiger populations are found in the Sundarbans—a large mangrove forest area shared by India and Bangladesh ..."},
            {id: 5,
                url: "https://www.tiger.nl/en-gb/",
                breadcrumb: "https://www.tiger.nl > en-gb",        
                title: "Tiger",
                description: "A familiar space that suits your daily routines. It is the place where you get ready to start the day, refresh yourself to go out or unwind after a tiring day."},
            {id: 6,
                url: "https://www.britannica.com/animal/tiger",
                breadcrumb: "https://www.britannica.com > animal > tiger",        
                title: "tiger | Facts, Information, Pictures, & Habitat | Britannica",
                description: "tiger, (Panthera tigris), largest member of the cat family (Felidae), rivaled only by the lion (Panthera leo) in strength and ferocity."},
            {id: 7,
                url: "https://www.tigerofsweden.com/gb/",
                breadcrumb: "https://www.tigerofsweden.com > ...",        
                title: "Tiger of Sweden",
                description: "Shop Tiger of Sweden. Buy clothing with a different clean cut, high quality materials and a proud attitude. Scandinavian Fashion brand for Men and Women."},
            {id: 8,
                url: "https://www.netflix.com/gb/title/81115994",
                breadcrumb: "https://www.netflix.com > title",        
                title: "Watch Tiger King | Netflix Official Site",
                description: "Tiger King. 2020 | TV-MA | 2 Seasons | Crime TV Shows. A zoo owner spirals out of control amid a cast of eccentric characters in this true murder-for-hire ..."},
            {id: 9,
                url: "https://en.wiktionary.org/wiki/tiger",
                breadcrumb: "https://en.wiktionary.org > wiki > tiger",        
                title: "tiger - Wiktionary",
                description: "NounEdit · Panthera tigris, a large predatory mammal of the cat family, indigenous to Asia. · (heraldry) A representation of a large mythological cat, used on a ..."},
            {id: 10,
                url: "https://www.tiger-technology.com/",
                breadcrumb: "https://www.tiger-technology.com",        
                title: "Tiger Technology: Home",
                description: "Your data management strategy has never mattered more. Tiger Technology gives you the tools that help you optimize your storage infrastructure."}
        ]},
    {item:"koala",
        results: [
            {id: 1,
                url: "",
                breadcrumb: "",        
                title: "",
                description: ""},
            {id: 2,
                url: "",
                breadcrumb: "",        
                title: "",
                description: ""},
            {id: 3,
                url: "",
                breadcrumb: "",        
                title: "",
                description: ""},
            {id: 4,
                url: "",
                breadcrumb: "",        
                title: "",
                description: ""},
            {id: 5,
                url: "",
                breadcrumb: "",        
                title: "",
                description: ""},
            {id: 6,
                url: "",
                breadcrumb: "",        
                title: "",
                description: ""},
            {id: 7,
                url: "",
                breadcrumb: "",        
                title: "",
                description: ""},
            {id: 8,
                url: "",
                breadcrumb: "",        
                title: "",
                description: ""},
            {id: 9,
                url: "",
                breadcrumb: "",        
                title: "",
                description: ""},
            {id: 10,
                url: "",
                breadcrumb: "",        
                title: "",
                description: ""}
        ]}
]
