const google = [
    {id: 1,
    url: "https://en.wikipedia.org/wiki/Turtle",
    breadcrumb: "https://en.wikipedia.org > wiki > Turtle",        
    title: "Turtle - Wikipedia",
    description: "Turtles are an order of reptiles known as Testudines, characterized by a shell developed mainly from their ribs. Modern turtles are divided into two major ..."},
    {id: 2,
        url: "https://www.britannica.com/animal/turtle-reptile",
        breadcrumb: "https://www.britannica.com > ... > Reptile",        
        title: "turtle | Species, Classification, & Facts | Britannica",
        description: "turtle, (order Testudines), any reptile with a body encased in a bony shell, including tortoises. Although numerous animals, from invertebrates to mammals, ..."},
    {id: 3,
        url: "https://www.britannica.com/story/whats-the-difference-between-a-turtle-and-a-tortoise",
        breadcrumb: "https://www.britannica.com > Demystified > Science",        
        title: "What's the Difference Between a Turtle and a Tortoise?",
        description: "All tortoises are in fact turtles—that is, they belong to the order Testudines or Chelonia, reptiles having bodies encased in a bony shell—but not all turtles ..."},
    {id: 4,
        url: "https://www.worldwildlife.org/species/sea-turtle",
        breadcrumb: "https://www.worldwildlife.org > species > sea-turtle",        
        title: "Sea Turtle | Species | WWF - World Wildlife Fund",
        description: "Sea turtles are the live representatives of a group of reptiles that have existed on Earth and traveled our seas for the last 100 million years. Turtles have ..."},
    {id: 5,
        url: "https://docs.python.org/3/library/turtle.html",
        breadcrumb: "https://docs.python.org > library > turtle",        
        title: "turtle — Turtle graphics — Python 3.10.7 documentation",
        description: "Turtle graphics is a popular way for introducing programming to kids. ... Turtle can draw intricate shapes using programs that repeat simple moves."},
    {id: 6,
        url: "https://en.wiktionary.org/wiki/turtle",
        breadcrumb: "https://en.wiktionary.org > wiki > turtle",        
        title: "turtle - Wiktionary",
        description: "NounEdit · (zoology, US, Canada) Any land or marine reptile of the order Testudines, characterised by a protective shell enclosing its body. · (zoology, Australia ..."},
    {id: 7,
        url: "https://www.wwf.org.uk/learn/fascinating-facts/marine-turtles",
        breadcrumb: "https://www.wwf.org.uk > learn > fascinating-facts > ma...",        
        title: "Top 10 facts about marine turtles - WWF-UK",
        description: "There are seven species of marine turtle. Marine turtles were around more than 100 million years ago - and lived alongside dinosaurs. These days, scientists ..."},
    {id: 8,
        url: "https://emojipedia.org/turtle/",
        breadcrumb: "https://emojipedia.org > turtle",        
        title: "Turtle Emoji - Emojipedia",
        description: "Emoji Meaning. A turtle, a slow-moving reptile with a shell. Depicted as a light-green turtle in full profile on all fours facing left, ..."},
    {id: 9,
        url: "https://www.seeturtles.org/why-are-sea-turtles-important",
        breadcrumb: "https://www.seeturtles.org > why-are-sea-turtles-important",        
        title: "Why Are Sea Turtles Important",
        description: "Turtle nesting helps beaches. The nutrients left behind by eggs and hatchlings that don't survive provide an important source for coastal vegetation. Hatchlings ..."},
    {id: 10,
        url: "http://seaturtle.org/",
        breadcrumb: "http://seaturtle.org",        
        title: "SEATURTLE.ORG - Global Sea Turtle Network",
        description: "Organizing the world's sea turtle information and making it universally accessible and useful."},
    {id: 11,
        url: "https://flyingtiger.com/",
        breadcrumb: "https://flyingtiger.com",        
        title: "Flying Tiger Copenhagen - Shop Online",
        description: "At Flying Tiger Copenhagen, we design products to make you feel good - Find inspirational products in our new webshop. Flying Tiger Copenhagen."},
    {id: 12,
        url: "https://en.wikipedia.org/wiki/Tiger",
        breadcrumb: "https://en.wikipedia.org > wiki > Tiger",        
        title: "Tiger - Wikipedia",
        description: "The tiger (Panthera tigris) is the largest living cat species and a member of the genus Panthera. It is most recognisable for its dark vertical stripes on ..."},
    {id: 13,
        url: "https://en.wikipedia.org/wiki/Tiger_I",
        breadcrumb: "https://en.wikipedia.org > wiki > Tiger_I",        
        title: "Tiger I - Wikipedia",
        description: "The Tiger I ( listen (help·info)) was a German heavy tank of World War II that operated beginning in 1942 in Africa and in the Soviet Union, usually in ..."},
    {id: 14,
        url: "https://www.worldwildlife.org/species/tiger",
        breadcrumb: "https://www.worldwildlife.org > species > tiger",        
        title: "Tiger | Species | WWF - World Wildlife Fund",
        description: "One of the world's largest, and most uniquely-adapted, tiger populations are found in the Sundarbans—a large mangrove forest area shared by India and Bangladesh ..."},
    {id: 15,
        url: "https://www.tiger.nl/en-gb/",
        breadcrumb: "https://www.tiger.nl > en-gb",        
        title: "Tiger",
        description: "A familiar space that suits your daily routines. It is the place where you get ready to start the day, refresh yourself to go out or unwind after a tiring day."},
    {id: 16,
        url: "https://www.britannica.com/animal/tiger",
        breadcrumb: "https://www.britannica.com > animal > tiger",        
        title: "tiger | Facts, Information, Pictures, & Habitat | Britannica",
        description: "tiger, (Panthera tigris), largest member of the cat family (Felidae), rivaled only by the lion (Panthera leo) in strength and ferocity."},
    {id: 17,
        url: "https://www.tigerofsweden.com/gb/",
        breadcrumb: "https://www.tigerofsweden.com > ...",        
        title: "Tiger of Sweden",
        description: "Shop Tiger of Sweden. Buy clothing with a different clean cut, high quality materials and a proud attitude. Scandinavian Fashion brand for Men and Women."},
    {id: 18,
        url: "https://www.netflix.com/gb/title/81115994",
        breadcrumb: "https://www.netflix.com > title",        
        title: "Watch Tiger King | Netflix Official Site",
        description: "Tiger King. 2020 | TV-MA | 2 Seasons | Crime TV Shows. A zoo owner spirals out of control amid a cast of eccentric characters in this true murder-for-hire ..."},
    {id: 19,
        url: "https://en.wiktionary.org/wiki/tiger",
        breadcrumb: "https://en.wiktionary.org > wiki > tiger",        
        title: "tiger - Wiktionary",
        description: "NounEdit · Panthera tigris, a large predatory mammal of the cat family, indigenous to Asia. · (heraldry) A representation of a large mythological cat, used on a ..."},
    {id: 20,
        url: "https://www.tiger-technology.com/",
        breadcrumb: "https://www.tiger-technology.com",        
        title: "Tiger Technology: Home",
        description: "Your data management strategy has never mattered more. Tiger Technology gives you the tools that help you optimize your storage infrastructure."},
    {id: 21,
        url: "https://en.wikipedia.org/wiki/Koala",
        breadcrumb: "https://en.wikipedia.org > wiki > Koala",        
        title: "Koala - Wikipedia",
        description: "The koala or, inaccurately, koala bear (Phascolarctos cinereus) is an arboreal herbivorous marsupial native to Australia. It is the only extant ..."},
    {id: 22,
        url: "https://www.nationalgeographic.com/animals/mammals/facts/koala",
        breadcrumb: "https://www.nationalgeographic.com > mammals > koala",        
        title: "Koala, facts and photos - National Geographic",
        description: "The koala is an iconic Australian animal. Often called the koala “bear,” this tree-climbing animal is a marsupial—a mammal with a pouch for the development of ..."},
    {id: 23,
        url: "https://www.britannica.com/animal/koala",
        breadcrumb: "https://www.britannica.com > ... > Mammals > Marsupials",        
        title: "koala | Appearance, Diet, Habitat, & Facts | Britannica",
        description: "29 Aug 2022 — koala, (Phascolarctos cinereus), also called koala bear, tree-dwelling marsupial of coastal eastern and southern Australia classified in the ..."},
    {id: 24,
        url: "https://www.natgeokids.com/uk/discover/animals/general-animals/ten-facts-about-koalas/",
        breadcrumb: "https://www.natgeokids.com > ten-facts-about-koalas",        
        title: "10 fascinating koala facts! | National Geographic Kids",
        description: ""},
    {id: 25,
        url: "https://www.wwf.org.uk/learn/fascinating-facts/koala",
        breadcrumb: "https://www.wwf.org.uk > fascinating-facts > koala",        
        title: "Top 10 facts about Koalas - WWF",
        description: "Koalas are endemic to Australia, where they can only be found in the southeast and eastern parts of the country, along the coastlines of Queensland, New South ..."},
    {id: 26,
        url: "https://zoo.sandiegozoo.org/cams/koala-cam",
        breadcrumb: "https://zoo.sandiegozoo.org > cams > koala-cam",        
        title: " Koala Cam - San Diego Zoo Wildlife Alliance",
        description: "While it's dark, from 7:30 p.m. to 7:30 a.m. we rebroadcast that morning's stream. Learn more about koalas · Read Koala Blog. Go Wild for Miles and Miles ..."},
    {id: 27,
        url: "https://animals.sandiegozoo.org/animals/koala",
        breadcrumb: "https://animals.sandiegozoo.org > animals > koala",        
        title: "Koala | San Diego Zoo Animals & Plants",
        description: "They are members of a group of pouched mammals called marsupials. Marsupials include kangaroos, wallabies, wallaroos, wombats, possums, and opossums. Koalas ..."},
    {id: 28,
        url: "https://environment.des.qld.gov.au/wildlife/animals/living-with/koalas/facts",
        breadcrumb: "https://environment.des.qld.gov.au > living-with > koalas",        
        title: "Koala facts - Queensland (Department of Environment",
        description: "24 Mar 2022 — Koalas are a type of mammal called marsupials, which give birth to underdeveloped young. They are so different from any other marsupial, however ..."},
    {id: 29,
        url: "https://www.edinburghzoo.org.uk/webcams/koala-cam/",
        breadcrumb: "https://www.edinburghzoo.org.uk > webcams > koala-c...",        
        title: " Koala Cam - Edinburgh Zoo",
        description: "Thank you for watching our koala cam - and thank you to everyone supporting Edinburgh Zoo by donating. Tanami is one of our Queensland koalas and his hobbies .."},
    {id: 30,
        url: "http://www.edgeofexistence.org/species/koala/",
        breadcrumb: "http://www.edgeofexistence.org > species > koala",        
        title: " Koala | Phascolarctos cinereus - EDGE of Existence",
        description: "Koalas are marsupials, and are the only living species in their family, Phascolarctidae, wombats are their closest living relatives. As marsupials, they give ..."}
]

module.exports = google
